#!/usr/bin/env bash

ROS_SBCL_PATH=`rospack find sbcl 2>&-`
if [ -n "$ROS_SBCL_PATH" ]; then
  SBCL_CMD=$ROS_SBCL_PATH/scripts/run-sbcl.sh
else
  SBCL_CMD="/usr/bin/env sbcl"
fi

ROSLISP_PATH=`rospack find roslisp`
if [ -z "$ROSLISP_PATH" ]; then
  echo "roslisp not found"
  exit 1
fi

if [[ $# == 4 ]]; then
  pkg=$1
  system=$2
  entry=$3
  output=$4
  echo "Generating Lisp executable."
  $SBCL_CMD --noinform --end-runtime-options --noprint --non-interactive \
            --load $ROSLISP_PATH/scripts/roslisp-sbcl-init \
            --load $ROSLISP_PATH/scripts/make-roslisp-exec.lisp \
                   $pkg $system $entry $output.lisp \
            --script \
      || exit $?
  cat > $output <<EOF
#!/bin/bash
ROS_SBCL_PATH=\`rospack find sbcl 2>&-\`
ROSLISP_PATH=\`rospack find roslisp\`
if [ -z "\$ROSLISP_PATH" ]; then
  echo "roslisp not found"
  exit 1
fi
if [ -n "\$ROS_SBCL_PATH" ]; then
  SBCL=\$ROS_SBCL_PATH/scripts/run-sbcl.sh
else
  SBCL="/usr/bin/env sbcl"
fi

ROSLISP_CURRENT_PACKAGE=$pkg \$SBCL --noinform --end-runtime-options --noprint --no-userinit --disable-debugger --load \$ROSLISP_PATH/scripts/roslisp-sbcl-init --load $output.lisp --end-toplevel-options \$*
EOF
  chmod a+x $output
else
  echo "Usage: make_node_exec <pkg> <system> <entry> <output>"
  exit 1
fi
